### ISSUE TITLE
code can not run successfully

### ISSUE THREAD

**Issue by weidong8405347** [titu1994/progressive-neural-architecture-search#1]
will occur error like this
in encoder.py
    value_idx = value_map[value]                                                                                        
TypeError: unhashable type: 'list' 

the value_map is value_map {0: 0, 1: 1, 2: 2, 3: 3, 4: 4} 
but value is [0, '1x7-7x1 conv', 0, '1x7-7x1 conv', 0, '1x7-7x1 conv', 0, '1x7-7x1 conv']

**Comment by heraldiclily** [comment]
Hello,
I'm working on a survey of meta-modelling approach for CNN architecture search. I faced the same error: 
value_idx = value_map[value]
TypeError: unhashable type: 'list'
Could you please indicate if you have been able to fix it?

**Comment by titu1994** [comment]
Sorry for the huge delay.  Could you try running it again? It works locally now.

@YasminaJaafra I have to remind you, this repository is not research code, only an example. I can assure you that it does not replicate the original paper by a long shot. 

If you wish to use Architecture search, I advice you to look at Efficient NAS code available in Tensorflow and modify it to fit your needs.
