### ISSUE TITLE
Usage Questions

### ISSUE THREAD

**Issue by impulsecorp** [titu1994/progressive-neural-architecture-search#3]
1. When it is done, it tells me this:
---------------------
Trial 5: Encoder loss : 0.000400
No more updates necessary as max B has been reached !
Finished !
---------------------
Do I then look at train_history.csv and pick the nn with highest accuracy score as the winner?

2.  I want to try it with MNIST. When I change train.py to use
 (x_train, y_train), (x_test, y_test) = mnist.load_data()
it starts working but then gives this error because MNIST has different dimensions that CIFAR10:
-------------------------------
Traceback (most recent call last):
  File "train.py", line 82, in <module>
    reward = manager.get_rewards(model_fn, state_space.parse_state_space_list(action))
  File "/home/ubuntu/pnas/manager.py", line 75, in get_rewards
    save_weights_only=True)])
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1630, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1476, in _standardize_user_data
    exception_prefix='input')
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 113, in _standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (60000, 28, 28)
------------------------------------

I know the inputs are:
CIFAR-10:  32x32 RGB images (so input size is 32x32x3=3072)
MNIST: 32x32 grayscale images (32x32x1=1024)

so in models.py I tried changing it from
ip = Input(shape=(32, 32, 3))
to
ip = Input(shape=(32, 32, 1))
but that did not help.  What do I change to make this work?

**Comment by impulsecorp** [comment]
Sorry, I found the answer to my first of the two questions, which is to use rank_architectures.py to find the winning nn.

**Comment by titu1994** [comment]
The answer to the second question is that you have to use reshape the MNIST Dataset to be (60000, 28, 28, 1) by using np.reshape or np.expand_dims(x, -1).

**Comment by impulsecorp** [comment]
I am not really sure what I am doing, but this worked:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = np.expand_dims(x_train, -1)
x_test = np.expand_dims(x_test, -1)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
