### ISSUE TITLE
Tensor shape mismatch when running train.py

### ISSUE THREAD

**Issue by bgreal5** [titu1994/progressive-neural-architecture-search#8]
Just running train.py out of the box, I'm seeing this log after it finishes models and starts training the controller: 

```Traceback (most recent call last):
  File "train.py", line 93, in <module>
    loss = controller.train_step(rewards)
  File "/home/bgreenwood/repos/progressive-neural-architecture-search/encoder.py", line 595, in train_step
    rnn_scores, states = self.controller(state_list, states=None)
  File "/home/bgreenwood/miniconda3/envs/pnas/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/bgreenwood/repos/progressive-neural-architecture-search/encoder.py", line 365, in call
    embed_ops = self.operators_embedding(operators)
  File "/home/bgreenwood/miniconda3/envs/pnas/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 746, in __call__
    self.build(input_shapes)
  File "/home/bgreenwood/miniconda3/envs/pnas/lib/python3.6/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 149, in wrapper
    output_shape = fn(instance, input_shape)
  File "/home/bgreenwood/miniconda3/envs/pnas/lib/python3.6/site-packages/tensorflow/python/keras/layers/embeddings.py", line 135, in build
    constraint=self.embeddings_constraint)
  File "/home/bgreenwood/miniconda3/envs/pnas/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 609, in add_weight
    aggregation=aggregation)
  File "/home/bgreenwood/miniconda3/envs/pnas/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 621, in _add_variable_with_custom_getter
    name=name, shape=shape)
  File "/home/bgreenwood/miniconda3/envs/pnas/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 687, in _preload_simple_restoration
    checkpoint_position=checkpoint_position, shape=shape)
  File "/home/bgreenwood/miniconda3/envs/pnas/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 83, in __init__
    self.wrapped_value.set_shape(shape)
  File "/home/bgreenwood/miniconda3/envs/pnas/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 927, in set_shape
    (self.shape, shape))
ValueError: Tensor's shape (3, 20) is not compatible with supplied shape (7, 20)```

**Comment by jackiechen0708** [comment]
I also encounter the same problem, have you solved this problem?

**Comment by jackiechen0708** [comment]
> Just running train.py out of the box, I'm seeing this log after it finishes models and starts training the controller:
> 
> ```
>   File "train.py", line 93, in <module>
>     loss = controller.train_step(rewards)
>   File "/home/bgreenwood/repos/progressive-neural-architecture-search/encoder.py", line 595, in train_step
>     rnn_scores, states = self.controller(state_list, states=None)
>   File "/home/bgreenwood/miniconda3/envs/pnas/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 757, in __call__
>     outputs = self.call(inputs, *args, **kwargs)
>   File "/home/bgreenwood/repos/progressive-neural-architecture-search/encoder.py", line 365, in call
>     embed_ops = self.operators_embedding(operators)
>   File "/home/bgreenwood/miniconda3/envs/pnas/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 746, in __call__
>     self.build(input_shapes)
>   File "/home/bgreenwood/miniconda3/envs/pnas/lib/python3.6/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 149, in wrapper
>     output_shape = fn(instance, input_shape)
>   File "/home/bgreenwood/miniconda3/envs/pnas/lib/python3.6/site-packages/tensorflow/python/keras/layers/embeddings.py", line 135, in build
>     constraint=self.embeddings_constraint)
>   File "/home/bgreenwood/miniconda3/envs/pnas/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 609, in add_weight
>     aggregation=aggregation)
>   File "/home/bgreenwood/miniconda3/envs/pnas/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 621, in _add_variable_with_custom_getter
>     name=name, shape=shape)
>   File "/home/bgreenwood/miniconda3/envs/pnas/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 687, in _preload_simple_restoration
>     checkpoint_position=checkpoint_position, shape=shape)
>   File "/home/bgreenwood/miniconda3/envs/pnas/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 83, in __init__
>     self.wrapped_value.set_shape(shape)
>   File "/home/bgreenwood/miniconda3/envs/pnas/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 927, in set_shape
>     (self.shape, shape))
> ValueError: Tensor's shape (3, 20) is not compatible with supplied shape (7, 20)```
> ```

**Comment by jackiechen0708** [comment]
@bgreal5 I also encounter the same problem, have you solved this problem?

**Comment by titu1994** [comment]
What version of Tensorflow is installed ? This codebase required TF 1.12 now as it is built on Eager Execution. 

Did you modify or uncomment the statespace to be larger ? In that case, you can't use the load_controller as the weights are built for the small architecture.

**Comment by bgreal5** [comment]
I'm using exactly TF 1.12.0 along with tensorflow-gpu 1.12.0 as well. 

I did not modify the code at all... this is just running `train.py` straight out of the box.

I'm on Ubuntu 16.04.5 if that matters.

**Comment by titu1994** [comment]
This was my bad. Uncomment the line 29, where it says mini search space. That's what I trained on and the weights it tries to load are from training on that. 

If you set RESTORE_CONTROLLER to False, you will not get any issues. If you just want to train on the small search space, uncomment the mini search h space.

**Comment by bgreal5** [comment]
Important to note RESTORE_CONTROLLER in `score_architectures.py` also needs to be set to False, or either lines 21-22 or line 24 in `score_architectures.py` need to be commented out depending on your operator space. (in this version at least, but I'm sure @titu1994 will update soon since he's been very prompt in resolving this issue!).

**Comment by titu1994** [comment]
Actually in score_architectures.py, the RESTORE_CONTROLLER needs to be set always, otherwise you would get random results from scoring. 

In that script, the only option is to correctly comment or uncomment the choice of operators.
